# Admin site configuration

addons: [ Authentication, Admin ]
navbar:
  brand: Reboot CMS
  structure:
    Pages: /pages
    Media: /media
    Admin:
      Site Configuration: /config
      Users: /users
      System Health: /health
      Update: /update