# Admin site configuration

addons: [ Authentication, Admin ]
navbar:
  brand: Reboot CMS
  structure:
    Pages: /pages
    Media: /media
    Site Configuration: /config
    Users: /users
    Update: /update